# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Save.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Save(object):
    def setupUi(self, Save):
        Save.setObjectName("Save")
        Save.resize(420, 170)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Save.sizePolicy().hasHeightForWidth())
        Save.setSizePolicy(sizePolicy)
        Save.setMinimumSize(QtCore.QSize(420, 170))
        Save.setMaximumSize(QtCore.QSize(420, 170))
        self.buttonBox = QtWidgets.QDialogButtonBox(Save)
        self.buttonBox.setGeometry(QtCore.QRect(110, 110, 200, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label_no = QtWidgets.QLabel(Save)
        self.label_no.setGeometry(QtCore.QRect(20, 20, 391, 81))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        font.setKerning(True)
        self.label_no.setFont(font)
        self.label_no.setMouseTracking(True)
        self.label_no.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_no.setTextFormat(QtCore.Qt.RichText)
        self.label_no.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_no.setWordWrap(True)
        self.label_no.setObjectName("label_no")

        self.retranslateUi(Save)
        self.buttonBox.accepted.connect(Save.accept) # type: ignore
        self.buttonBox.rejected.connect(Save.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Save)

    def retranslateUi(self, Save):
        _translate = QtCore.QCoreApplication.translate
        Save.setWindowTitle(_translate("Save", "Сохранение"))
        self.label_no.setText(_translate("Save", "<html><head/><body><p><span style=\" font-weight:600;\">Полученные значения сохранены в &quot;Data.xlsx&quot;</span></p><p>Скопируйте этот файл в другую директорию перед следующим использованием программы.</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Save = QtWidgets.QDialog()
    ui = Ui_Save()
    ui.setupUi(Save)
    Save.show()
    sys.exit(app.exec_())
